apiVersion: v1
kind: Service
metadata:
  name: pokenum-service
spec:
  selector:
    app: pokenum
  ports:
  - name: uvicorn-port
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: flask-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer